export const texts = {
  largeTitle: {
    minHeight: 41,
    fontSize: 34,
    lineHeight: 41,
    letterSpacing: -0.4,
  },
  largeTitleEmphasized: {
    minHeight: 41,
    fontSize: 34,
    lineHeight: 41,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  title: {
    minHeight: 34,
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.4,
  },
  titleEmphasized: {
    minHeight: 34,
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },

  secondaryTitle: {
    minHeight: 28,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.4,
  },
  secondaryTitleEmphasized: {
    minHeight: 28,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  tertiaryTitle: {
    minHeight: 25,
    fontSize: 20,
    lineHeight: 25,
    letterSpacing: -0.4,
  },
  tertiaryTitleEmphasized: {
    minHeight: 25,
    fontSize: 20,
    lineHeight: 25,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  headline: {
    minHeight: 22,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.4,
    fontWeight: 'semibold',
  },
  HeadlineItalic: {
    minHeight: 22,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.4,
    fontWeight: 'semibold',
    fontStyle: 'italic',
  },
  body: {
    minHeight: 22,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.4,
  },
  bodyItalic: {
    minHeight: 22,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.4,
    fontStyle: 'italic',
  },
  bodyEmphasized: {
    minHeight: 22,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  bodyEmphasizedItalic: {
    minHeight: 22,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  callout: {
    minHeight: 21,
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: -0.4,
  },
  calloutItalic: {
    minHeight: 21,
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: -0.4,
    fontStyle: 'italic',
  },
  calloutEmphasized: {
    minHeight: 21,
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  calloutEmphasizedItalic: {
    minHeight: 21,
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  subHeadline: {
    minHeight: 20,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.4,
  },
  subHeadlineItalic: {
    minHeight: 20,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.4,
    fontStyle: 'italic',
  },
  subHeadlineEmphasized: {
    minHeight: 20,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  subHeadlineEmphasizedItalic: {
    minHeight: 20,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  footnote: {
    minHeight: 18,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.4,
  },
  footnoteItalic: {
    minHeight: 18,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.4,
    fontStyle: 'italic',
  },
  footnoteEmphasized: {
    minHeight: 18,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  footnoteEmphasizedItalic: {
    minHeight: 18,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  caption: {
    minHeight: 16,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.4,
  },
  captionItalic: {
    minHeight: 16,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.4,
    fontStyle: 'italic',
  },
  captionEmphasized: {
    minHeight: 16,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  captionEmphasizedItalic: {
    minHeight: 16,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  secondaryCaption: {
    minHeight: 13,
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: -0.4,
  },
  secondaryCaptionItalic: {
    minHeight: 13,
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: -0.4,
    fontStyle: 'italic',
  },
  secondaryCaptionEmphasized: {
    minHeight: 13,
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: -0.4,
    fontWeight: 'bold',
  },
  secondaryCaptionEmphasizedItalic: {
    minHeight: 13,
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
}

export type TextType = keyof typeof texts
